esphome:
  name: weather-station-sensor

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "af79a97400992b1cad6615be4d8f98b5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Weather-Station-Sensor"
    password: "hXHCM7pfVumm"

captive_portal:
    
i2c:
  sda: GPIO4
  scl: GPIO5
  
sensor:
  - platform: shtcx
    temperature:
      name: "Outside Temperature"
    humidity:
      name: "Outside Humidity"
    address: 0x70
    update_interval: 30s