esphome:
  name: aquariums

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "cb15de644640cf7a95c63ac888c6280e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aquariums Fallback Hotspot"
    password: "bIlGgZgmWCi1"

captive_portal:

switch:
  - platform: gpio
    name: "Heating Bulb"
    pin:
      number: 0
      inverted: true
      
  - platform: gpio
    name: "Turtle Lights"
    pin:
      number: 1
      inverted: false
      
  - platform: gpio
    name: "Fish Lights"
    pin:
      number: 3
      inverted: true